<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.11.7/video-js.min.css" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.11.7/video.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/videojs-contrib-eme@3.8.0/dist/videojs-contrib-eme.js"></script>

    <title>Test VideJS DRM</title>
</head>
<body>
<?php // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-services.freecast.com/live/api/v5/web/packages/value/channels/sc-385007/streams/');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: api-services.freecast.com';
$headers[] = 'Accept: application/json, text/plain, */*';
$headers[] = 'Accept-Language: en-US,en;q=0.9';
$headers[] = 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU4NzY3OTI1LCJqdGkiOiIwNDkyYzg2NTZjYTk0ODRlOWI5MzgyMmVlZmM1Mjg2YyIsInVzZXJfaWQiOjQxNTA5N30.bJkj5mTP3FygNix_utVvUDSncYrFPT0-VlGKj1w2RZU';
$headers[] = 'Origin: https://selecttv.freecast.com';
$headers[] = 'Referer: https://selecttv.freecast.com/';
$headers[] = 'Sec-Ch-Ua: ^^.Not/A)Brand^^\";v=^^\"99^^\",';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
$headers[] = 'Sec-Fetch-Dest: empty';
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Sec-Fetch-Site: same-site';
$headers[] = 'Sotalcloud-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlNDVrNG1qTlcyVm5XZEhMV2NPQTBXSE1ybFlEZXU1In0.To9pY-N0_XWBUNpFPbKZCKV23VbUSP7H515g9eM3Fsw';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
// Replaces all "quotations" with random code
$replace = str_replace('"', 'KKK1', $result);
// Explodes in to array by random code
$str_arr = explode ("KKK1", $replace); 
//print_r($str_arr);
//echo $str_arr[61];
//echo $str_arr[71];
?>

    <div style="margin: 50px auto;">
        <video id="my-video" class="video-js"></video>
    </div>



    <script>
        var strm = <?php echo $str_arr[61]; ?>; //outputting string foo in context of JS
		var cert = '<?php echo $str_arr[71]; ?>'; //outputting string foo in context of JS
                                 //must wrap in quotes so that it is still string foo when JS does execute
                                 //when this DOES execute in the browser, PHP will have already completed all processing and exited
        var player = videojs(
            'my-video',
            {
                controls: true,
                fluid: true,
                html5: {
                    vhs: { 
                        overrideNative: true 
                    }
                }
            },
            function() {
                var player = this;
                player.eme();
                player.src({
                    src: 'strm',
                    type: 'application/dash+xml',                    
                    keySystems: {
                      'com.widevine.alpha': 'cert',                     
                    }
                });

            
                player.ready(function() {

                    player.tech(true).on('keystatuschange', function(event) {    
                        console.log("event: ", event);        

                    });                        

                });                
            }            
        
        );        


    </script>
</body>
</html>
