<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Test Flight</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/dashjs/4.4.1/dash.all.debug.min.js"></script>

    <!-- Bootstrap core CSS -->
    <link href="bootstrap.min.css" rel="stylesheet">
    <link href="main.css" rel="stylesheet">

    <style>
        video {
            width: 100%;
        }
    </style>
<?php // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$auth = file_get_contents("../files/tokens/selecttv-auth.txt");
$token = file_get_contents("../files/tokens/selecttv-token.txt");
$poop = 'Authorization: Bearer $auth';
echo $auth;
echo $token;
echo $poop;
?>

  <?php echo $str_arr[71]; ?>
</body>
</html>
